# Generated by Django 4.2.9 on 2024-01-03 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('champions', models.TextField(max_length=30)),
                ('kills', models.TextField(max_length=30)),
                ('deaths', models.TextField(max_length=100)),
                ('assists', models.TextField(max_length=30)),
                ('results', models.TextField(max_length=30)),
                ('position', models.TextField(max_length=30)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
